### ISSUE TITLE
Dpi scaling issue in Windows 10 11

### ISSUE THREAD

**Issue by Mika3578** [ansani/Shareaza#52]
<img width="339" alt="Capture d’écran 2022-10-29 135135" src="https://user-images.githubusercontent.com/58137747/198830293-95a19831-4ef3-4853-9f9a-0a6143973926.png">
<img width="424" alt="Capture d’écran 2022-10-29 135528" src="https://user-images.githubusercontent.com/58137747/198830295-31b1ea86-50c1-47ec-b978-9962e9ef914f.png">
Impossible to select hide value
all setting in Windows setting do nothing
no problem with official build 2.7.10.2 x64

**Comment by ansani** [comment]
Hi Mika!
Your monitor resolution?

**Comment by Mika3578** [comment]
1920x1080

**Comment by ansani** [comment]
> 1920x1080

Do you have a scaling? (i.e. 125% or something like that)

**Comment by Mika3578** [comment]
I try all sacling value 100 to 150 do nothing

**Comment by kamil445** [comment]
I have this same issue o **beta4**, i have 1280x1024 screen resolution.

**Beta3** working 4 days in a row without any issues for now :)

**Comment by ansani** [comment]
> I have this same issue on **beta4**, i have 1280x1024 screen resolution and Windows 7 x64.

I fixed this in the upcoming release.


> 
> 
> 
> **Beta3** working 4 days in a row without any issues for now :)

Great!!! 😎

**Comment by ansani** [comment]
Hi @kamil445 and @Mika3578 !
Can you check if this release fixes all things https://github.com/ansani/Shareaza/actions/runs/3378639881#artifacts ?

Thank you!
Salvatore

**Comment by Mika3578** [comment]
Ok for Dpi with iShareaza_2.7.10.4_x64_Release_2022-11-02
but still have issue with this item selection:
![S1](https://user-images.githubusercontent.com/58137747/199563274-cfbecdec-971c-4c07-869d-b1fcf0651f9b.PNG)
![S2](https://user-images.githubusercontent.com/58137747/199563282-56ceae9a-f7e9-4a86-980e-4b2884f81090.PNG)
 Thanks for your updates

**Comment by ansani** [comment]
> Ok for Dpi with iShareaza_2.7.10.4_x64_Release_2022-11-02

Glad to hear!

> 
> but still have issue with this item selection:
> 
> ![S1](https://user-images.githubusercontent.com/58137747/199563274-cfbecdec-971c-4c07-869d-b1fcf0651f9b.PNG)
> 
> ![S2](https://user-images.githubusercontent.com/58137747/199563282-56ceae9a-f7e9-4a86-980e-4b2884f81090.PNG)
> 

I hat is the issue with the dialog box?

**Comment by ansani** [comment]
@Mika3578 Can you point me to how to replicate the issue you noticed in the previous comment?
Thank you!
